import './globals';
import React from 'react';
import ReactDOM from 'react-dom/client';
import './index.css';
import App from './App';
import { registerLicense } from '@syncfusion/ej2-base';

registerLicense('Mgo+DSMBaFt+QHFqVk9rXVNbdV5dVGpAd0N3RGlcdlR1fUUmHVdTRHRcQlliTH5Xd0FhUXxbd3M=;Mgo+DSMBPh8sVXJ1S0d+X1hPd11dXmJWd1p/THNYflR1fV9DaUwxOX1dQl9gSXpSc0VnWHtceHdTT2c=;ORg4AjUWIQA/Gnt2VFhhQlJNfV5AQmBIYVp/TGpJfl96cVxMZVVBJAtUQF1hSn5Xd0BjXX5acnxWTmFb;MTczMjMxM0AzMjMxMmUzMTJlMzMzOW5UbzRQZVlzUXdrYkFGSFI5bXJxdDZleWRmYVMwSW8rTExNV1h3aEI2Qnc9;MTczMjMxNEAzMjMxMmUzMTJlMzMzOWpYNmg2SkxrQUZueGFRV1NlMmI2S2lHOFVucGJQLzFsUTFDSGZUMEkyM0U9;NRAiBiAaIQQuGjN/V0d+XU9Hf1RDX3xKf0x/TGpQb19xflBPallYVBYiSV9jS31TckRmWXtfdHZdQmReVg==;MTczMjMxNkAzMjMxMmUzMTJlMzMzOW5COUw1eWlkRnZHQ3ZodkMzUTJtRGN5Yk9zU2o2bzcrOG83MzY0dFRyUzQ9;MTczMjMxN0AzMjMxMmUzMTJlMzMzOVN0VHZqUFQwZU5MaklKMjczc0hDaWwxTi9aWTA4d2srRGVOMW16NUEyejQ9;Mgo+DSMBMAY9C3t2VFhhQlJNfV5AQmBIYVp/TGpJfl96cVxMZVVBJAtUQF1hSn5Xd0BjXX5acnxQR2Fb;MTczMjMxOUAzMjMxMmUzMTJlMzMzOUpyQVdtMURqT3hXMk5ORmNYM3IvbXhBY2M3UnFwanh1dkdIN2dsYjBKd0k9;MTczMjMyMEAzMjMxMmUzMTJlMzMzOW84VG0xQ0ZIZFZIOE93R3BxN1JmK0RzVzNmMmZNTWF4b01lclREcDVVZEE9;MTczMjMyMUAzMjMxMmUzMTJlMzMzOW5COUw1eWlkRnZHQ3ZodkMzUTJtRGN5Yk9zU2o2bzcrOG83MzY0dFRyUzQ9');
const root = ReactDOM.createRoot(
  document.getElementById('root') as HTMLElement
);
root.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);